#!/bin/bash

# Simplified Test Report Generation Script for Tondino
set -e

REPORT_DIR="test-reports"
TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
REPORT_FILE="$REPORT_DIR/test-report-$TIMESTAMP.md"

# Create reports directory
mkdir -p "$REPORT_DIR"

echo "🧪 Generating test report for Tondino project..."

# Start the report
cat > "$REPORT_FILE" << EOF
# Tondino Test Report

**Generated:** $(date)
**Branch:** $(git branch --show-current 2>/dev/null || echo 'Unknown')
**Commit:** $(git rev-parse --short HEAD 2>/dev/null || echo 'Unknown')
**Environment:** ${NODE_ENV:-development}

## Summary

EOF

# Track overall status
OVERALL_STATUS="PASS"

# Function to test command and add to report
test_component() {
    local name="$1"
    local command="$2"
    local directory="$3"
    
    echo "Testing $name..."
    
    if [ -n "$directory" ]; then
        cd "$directory"
    fi
    
    local start_time=$(date +%s)
    
    if eval "$command" >/dev/null 2>&1; then
        local end_time=$(date +%s)
        local duration=$((end_time - start_time))
        echo "### ✅ $name - PASSED (${duration}s)" >> "$REPORT_FILE"
    else
        local end_time=$(date +%s)
        local duration=$((end_time - start_time))
        echo "### ❌ $name - FAILED (${duration}s)" >> "$REPORT_FILE"
        OVERALL_STATUS="FAIL"
    fi
    
    if [ -n "$directory" ]; then
        cd - >/dev/null
    fi
    
    echo "" >> "$REPORT_FILE"
}

# Test Backend
echo "## Backend Tests" >> "$REPORT_FILE"
test_component "Backend TypeScript Compilation" "npx tsc --noEmit" "tondino-backend"
test_component "Backend Build" "npm run build" "tondino-backend"

# Only run backend integration tests if DB is available
if [[ -n "$DATABASE_URL" && -n "$JWT_SECRET" ]]; then
    test_component "Backend Integration Tests" "npm test" "tondino-backend"
else
    echo "### ⏭️ Backend Integration Tests - SKIPPED (No DATABASE_URL or JWT_SECRET)" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
fi

# Test Frontend
echo "## Frontend Tests" >> "$REPORT_FILE"
test_component "Frontend TypeScript Check" "npm run type-check" "tondino-frontend"
test_component "Frontend Build" "npm run build" "tondino-frontend"
test_component "Frontend Unit Tests" "npm run test:ci" "tondino-frontend"

# Security scan
echo "## Security" >> "$REPORT_FILE"
if [[ -f "./scripts/scan-secrets.sh" ]]; then
    test_component "Secret Scan" "./scripts/scan-secrets.sh" ""
else
    echo "### ⏭️ Secret Scan - SKIPPED (Script not found)" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
fi

# Project metrics
echo "## Project Metrics" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

backend_files=$(find tondino-backend/src -name "*.ts" | wc -l | tr -d ' ')
frontend_files=$(find tondino-frontend/src -name "*.tsx" -o -name "*.ts" | wc -l | tr -d ' ')
test_files=$(find . -name "*.test.*" -o -name "*.spec.*" | wc -l | tr -d ' ')

echo "- **Backend TypeScript Files:** $backend_files" >> "$REPORT_FILE"
echo "- **Frontend TypeScript Files:** $frontend_files" >> "$REPORT_FILE"
echo "- **Test Files:** $test_files" >> "$REPORT_FILE"
echo "- **Node.js Version:** $(node --version)" >> "$REPORT_FILE"
echo "- **npm Version:** $(npm --version)" >> "$REPORT_FILE"

# Dependencies
echo "" >> "$REPORT_FILE"
echo "## Dependencies" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

cd tondino-backend
backend_deps=$(npm list --depth=0 2>/dev/null | grep -c '├──\|└──' || echo "unknown")
cd ../tondino-frontend  
frontend_deps=$(npm list --depth=0 2>/dev/null | grep -c '├──\|└──' || echo "unknown")
cd ..

echo "- **Backend Dependencies:** $backend_deps" >> "$REPORT_FILE"
echo "- **Frontend Dependencies:** $frontend_deps" >> "$REPORT_FILE"

# Final status
echo "" >> "$REPORT_FILE"
echo "## Final Status: $OVERALL_STATUS" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

if [ "$OVERALL_STATUS" = "PASS" ]; then
    echo "✅ All critical tests passed! Ready for deployment." >> "$REPORT_FILE"
else
    echo "❌ Some tests failed. Please review and fix before merging." >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Report generated by: \`scripts/generate-simple-report.sh\`*" >> "$REPORT_FILE"

# Create symlink to latest
ln -sf "$(basename "$REPORT_FILE")" "$REPORT_DIR/latest.md"

echo "✅ Test report generated successfully!"
echo "📄 Report: $REPORT_FILE"
echo "🔗 Latest: $REPORT_DIR/latest.md"
echo ""
echo "📋 Overall Status: $OVERALL_STATUS"

if [ "$OVERALL_STATUS" = "FAIL" ]; then
    echo "❌ Some tests failed - check the report for details"
    exit 1
else
    echo "✅ All tests passed!"
    exit 0
fi