#!/bin/bash

# Working Test Report Generator for Tondino
set -e

echo "🧪 Generating Tondino Test Report..."

REPORT_DIR="test-reports"
TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')

# Create reports directory
mkdir -p "$REPORT_DIR"

REPORT_FILE="$REPORT_DIR/test-report-$TIMESTAMP.md"

{
    echo "# Tondino Test Report"
    echo ""
    echo "**Generated:** $(date)"
    echo "**Branch:** $(git branch --show-current 2>/dev/null || echo 'Unknown')"
    echo "**Commit:** $(git rev-parse --short HEAD 2>/dev/null || echo 'Unknown')"
    echo ""
    
    echo "## Build Tests"
    echo ""
    
    # Backend TypeScript Check
    echo -n "- **Backend TypeScript:** "
    if cd tondino-backend && npx tsc --noEmit >/dev/null 2>&1; then
        echo "✅ PASS"
    else
        echo "❌ FAIL"
    fi
    cd .. 2>/dev/null || true
    
    # Backend Build
    echo -n "- **Backend Build:** "
    if cd tondino-backend && npm run build >/dev/null 2>&1; then
        echo "✅ PASS"
    else
        echo "❌ FAIL"
    fi
    cd .. 2>/dev/null || true
    
    # Frontend TypeScript Check
    echo -n "- **Frontend TypeScript:** "
    if cd tondino-frontend && npm run type-check >/dev/null 2>&1; then
        echo "✅ PASS"
    else
        echo "❌ FAIL"
    fi
    cd .. 2>/dev/null || true
    
    # Frontend Build
    echo -n "- **Frontend Build:** "
    if cd tondino-frontend && npm run build >/dev/null 2>&1; then
        echo "✅ PASS"
    else
        echo "❌ FAIL"
    fi
    cd .. 2>/dev/null || true
    
    # Frontend Tests
    echo -n "- **Frontend Tests:** "
    if cd tondino-frontend && npm run test:ci >/dev/null 2>&1; then
        echo "✅ PASS"
    else
        echo "❌ FAIL"
    fi
    cd .. 2>/dev/null || true
    
    echo ""
    echo "## Environment Info"
    echo ""
    echo "- **Node.js:** $(node --version)"
    echo "- **npm:** $(npm --version)"
    echo "- **Platform:** $(uname -s)"
    echo ""
    
    echo "## Project Structure"
    echo ""
    backend_files=$(find tondino-backend/src -name "*.ts" 2>/dev/null | wc -l | tr -d ' ')
    frontend_files=$(find tondino-frontend/src -name "*.tsx" -o -name "*.ts" 2>/dev/null | wc -l | tr -d ' ')
    test_files=$(find . -name "*.test.*" -o -name "*.spec.*" 2>/dev/null | wc -l | tr -d ' ')
    
    echo "- **Backend Files:** $backend_files TypeScript files"
    echo "- **Frontend Files:** $frontend_files TypeScript/TSX files"  
    echo "- **Test Files:** $test_files test files"
    echo ""
    
    echo "---"
    echo "*Generated by: scripts/working-test-report.sh*"
} > "$REPORT_FILE"

# Create latest symlink
ln -sf "$(basename "$REPORT_FILE")" "$REPORT_DIR/latest.md"

echo "✅ Test report generated: $REPORT_FILE"
echo "🔗 Latest report: $REPORT_DIR/latest.md"
echo ""
echo "📄 Report contents:"
echo "---"
cat "$REPORT_FILE"